# Generated by Django 4.1.3 on 2023-01-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_created_date_variation_created_date'),
        ('carts', '0002_remove_cart_card_id_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_addded',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
