# Generated by Django 4.1.3 on 2023-05-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_created_date_variation_created_date'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='variation',
        ),
        migrations.AddField(
            model_name='order_product',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
